// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWke1baMIcd8vZD-66X5T_k3xf6prt3-Y',
    appId: '1:877769589306:web:7ecda5d28f21b581d66b03',
    messagingSenderId: '877769589306',
    projectId: 'portos-nextgen-harris-20260328',
    authDomain: 'portos-nextgen-harris-20260328.firebaseapp.com',
    storageBucket: 'portos-nextgen-harris-20260328.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn6okdKfNWY-actWAtQLxmguYA_EHgHG4',
    appId: '1:877769589306:android:f3afc865fe3a1c9bd66b03',
    messagingSenderId: '877769589306',
    projectId: 'portos-nextgen-harris-20260328',
    storageBucket: 'portos-nextgen-harris-20260328.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBqE6F_RL4PwZQPQ3q6onLgdpQob90huY',
    appId: '1:877769589306:ios:c5475069387d4d54d66b03',
    messagingSenderId: '877769589306',
    projectId: 'portos-nextgen-harris-20260328',
    storageBucket: 'portos-nextgen-harris-20260328.firebasestorage.app',
    iosClientId: '877769589306-3ep55gfv4v043513k64c5eq3ervjr4d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBqE6F_RL4PwZQPQ3q6onLgdpQob90huY',
    appId: '1:877769589306:ios:c5475069387d4d54d66b03',
    messagingSenderId: '877769589306',
    projectId: 'portos-nextgen-harris-20260328',
    storageBucket: 'portos-nextgen-harris-20260328.firebasestorage.app',
    iosClientId: '877769589306-3ep55gfv4v043513k64c5eq3ervjr4d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWke1baMIcd8vZD-66X5T_k3xf6prt3-Y',
    appId: '1:877769589306:web:7ecda5d28f21b581d66b03',
    messagingSenderId: '877769589306',
    projectId: 'portos-nextgen-harris-20260328',
    authDomain: 'portos-nextgen-harris-20260328.firebaseapp.com',
    storageBucket: 'portos-nextgen-harris-20260328.firebasestorage.app',
  );
}
